spring.application.name=tusmo

spring.datasource.url=jdbc:h2:file:./tusmo_db_data;AUTO_SERVER=TRUE;TRACE_LEVEL_FILE=0
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
